import { Document, Packer, Paragraph, HeadingLevel, AlignmentType } from 'docx';

export const generateHiringReport = async (reportData) => {
    const {
        companyName = 'All Companies',
        totalHires = 0,
        totalApplications = 0,
        pendingInterviews = 0,
        passedInterviews = 0,
        failedInterviews = 0,
        hiredApplicants = [],
        applicantsByStatus = {},
        generatedDate = new Date().toLocaleDateString()
    } = reportData;

    const doc = new Document({
        sections: [{
            children: [
                // Title
                new Paragraph({
                    text: 'HIRING ANALYTICS REPORT',
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 200 },
                }),

                // Company Info
                new Paragraph({
                    text: `Company: ${companyName}`,
                    spacing: { after: 100 },
                }),

                new Paragraph({
                    text: `Generated: ${generatedDate}`,
                    spacing: { after: 300 },
                }),

                // Summary heading
                new Paragraph({
                    text: 'EXECUTIVE SUMMARY',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { after: 200 },
                }),

                // Key metrics
                new Paragraph({
                    text: `Total Applications: ${totalApplications}`,
                    spacing: { after: 100 },
                }),

                new Paragraph({
                    text: `Total Hires: ${totalHires}`,
                    spacing: { after: 100 },
                }),

                new Paragraph({
                    text: `Pending Interviews: ${pendingInterviews}`,
                    spacing: { after: 100 },
                }),

                new Paragraph({
                    text: `Passed Interviews: ${passedInterviews}`,
                    spacing: { after: 100 },
                }),

                new Paragraph({
                    text: `Failed Interviews: ${failedInterviews}`,
                    spacing: { after: 300 },
                }),

                // Hired Applicants heading
                new Paragraph({
                    text: 'HIRED APPLICANTS',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { after: 200 },
                }),

                // Hired applicants list
                ...(hiredApplicants.length > 0
                    ? hiredApplicants.slice(0, 20).map((applicant, index) => 
                        new Paragraph({
                            text: `${index + 1}. ${applicant.fullname || 'N/A'} - ${applicant.jobTitle || 'N/A'} at ${applicant.companyName || 'N/A'} (${applicant.hireDate || 'N/A'})`,
                            spacing: { after: 80 },
                        })
                    )
                    : [new Paragraph({
                        text: 'No hired applicants to display.',
                        spacing: { after: 300 },
                    })]),

                new Paragraph({
                    text: '',
                    spacing: { after: 300 },
                }),

                // Status Distribution heading
                new Paragraph({
                    text: 'APPLICANT STATUS DISTRIBUTION',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { after: 200 },
                }),

                // Status distribution items
                ...(Object.keys(applicantsByStatus).length > 0
                    ? Object.entries(applicantsByStatus).map(([status, count]) =>
                        new Paragraph({
                            text: `${status}: ${count} applicants`,
                            spacing: { after: 100 },
                        })
                    )
                    : [new Paragraph({
                        text: 'No applicant data available.',
                        spacing: { after: 100 },
                    })]),

                new Paragraph({
                    text: '',
                    spacing: { after: 400 },
                }),

                // Footer
                new Paragraph({
                    text: '---',
                    spacing: { before: 300, after: 100 },
                }),

                new Paragraph({
                    text: 'This report was generated by the CAPSTONE Hiring Management System',
                    spacing: { after: 100 },
                    alignment: AlignmentType.CENTER,
                }),
            ],
        }],
    });

    return doc;
};

export const generateReportBuffer = async (doc) => {
    try {
        return await Packer.toBuffer(doc);
    } catch (error) {
        console.error('Error converting document to buffer:', error);
        throw error;
    }
};
